---
ghq_root: "{{ ansible_user_dir }}/.ghq/github.com"

git_repositories:
  - { repo: "https://github.com/registak/dotfiles.git", dest: "{{ ghq_root }}/registak/dotfiles" }
  - { repo: "https://github.com/tmux-plugins/tpm.git", dest: "{{ ansible_user_dir }}/.tmux/plugins/tpm" }
  - { repo: "https://github.com/drduh/pwd.sh.git", dest: "{{ ghq_root }}/drduh/pwd.sh" }
  - { repo: "https://github.com/aws/aws-cli.git", dest: "{{ ghq_root }}/aws/aws-cli" }


symlinks:
  - { src: "{{ ghq_root }}/drduh/pwd.sh/pwd.sh", dest: /usr/local/bin/pwd.sh }

setup_repositories:
  - { chdir: "{{ ansible_user_dir }}/.ghq/github.com/registak/dotfiles", creates: "{{ ansible_user_dir }}/.vimrc" }
