---
- name: Install ricty fonts
  shell: |
    cp -f $(brew --cellar ricty)/*/share/fonts/Ricty*.ttf ~/Library/Fonts && fc-cache -vf
  args:
    creates: "{{ ansible_user_dir }}/Library/Fonts/Ricty-Bold.ttf"

- name: Setup OS X defaults
  osx_defaults:
    domain: "{{ item.domain }}"
    key: "{{ item.key }}"
    type: "{{ item.type }}"
    value: "{{ item.value }}"
    state: present
  with_items:
    - "{{ osx_defaults }}"
