---
- name: setup nodebrew
  shell: |
    bash -cl 'nodebrew setup'

- name: Install Nodejs via nodebrew
  shell: |
    bash -cl 'nodebrew install-binary "{{ nodejs_version }}"'

- name: Check if Nodejs version is "{{ nodejs_version }}"
  shell: |
    bash -cl 'nodebrew ls' | grep -F "{{ nodejs_version }}"
  register: res
  always_run: yes
  failed_when: no
  changed_when: res.rc != 0
  notify:
    - Change Nodejs version

- name: Flush handlers
  meta: flush_handlers

- name: Install npm packages
  npm:
    name: "{{ item.name }}"
    global: yes
    state: present
  with_items:
    - "{{ npm_packages }}"
