---
- name: Change Ruby version
  shell: |
    bash -cl 'rbenv global "{{ ruby_version }}"'

- name: Rehash pyenv
  shell: |
    pyenv rehash

- name: Change Nodejs version
  shell: |
    bash -cl 'nodebrew use "{{ nodejs_version }}"'
